# Generated by Django 3.0.3 on 2020-02-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverrequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
